### ISSUE TITLE
Multi-Language and Multi-Sign Language Support

### ISSUE THREAD

**Issue by Abdul-Rahman-9040** [nitkhackathon2024-5/AIT-WeXpert#2]
Description: Expand the plugin's functionality to support multiple spoken and sign languages. This will help users in international virtual meetings to engage regardless of their spoken or sign language. Tasks:

Implement support for multiple spoken languages in the speech recognition engine.
Integrate additional sign language datasets (e.g., American Sign Language, British Sign Language).
Ensure that users can easily switch between languages during a meeting.

**Comment by Amaan9136** [comment]
I have implemented Multi-Language and Multi-Sign Language Support in the application, allowing users to switch between different regional sign languages and adjust the corresponding alphabet representation dynamically. Specifically, I have added American and British sign language support alongside the existing Indian sign language format.

Users can now choose from Indian, American, and British sign languages.
Each region has its own corresponding sign images for the alphabet, ensuring accurate representation based on the chosen region.
